[build]
  command = "npm run web:build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "PORT,JWT_SECRET,DATABASE_URL"

[[redirects]]
  from = "/api/*"
  to = "http://ec2-52-67-13-135.sa-east-1.compute.amazonaws.com:4000/api/:splat"
  status = 200
  force = true
